export const ONBOARDING_PHASE_SETUP = "setup";
export const ONBOARDING_PHASE_TOUR = "tour";

export const ONBOARDING_STEPS = [
  // Phase 1 — Profile setup (short, required)
  {
    id: "welcome",
    phase: ONBOARDING_PHASE_SETUP,
    route: "/profile",
    target: null,
    title: "Welcome to ArmPal",
    description:
      "Track your workouts, PRs, nutrition, and goals. Connect with friends and monitor your progress.",
    body:
      "Track your workouts, PRs, nutrition, and goals. Connect with friends and monitor your progress.",
    type: "modal",
    buttonText: "Next",
    blockInteraction: true,
    trigger: { type: "button", action: "start_profile" },
  },
  {
    id: "profile_intro",
    phase: ONBOARDING_PHASE_SETUP,
    route: "/profile",
    target: null,
    title: "Create your profile",
    description:
      "Create a name and handle to continue. The rest of the profile is optional. Tap Save once finished to start the tour.",
    body:
      "Create a name and handle to continue. The rest of the profile is optional. Tap Save once finished to start the tour.",
    type: "modal",
    buttonText: "Continue",
    blockInteraction: true,
    trigger: { type: "button", action: "start_profile_instructions" },
  },
  {
    id: "profile_edit",
    phase: ONBOARDING_PHASE_SETUP,
    route: "/profile",
    target: "[data-onboarding='display-handle-block']",
    title: "Set your profile",
    description: "Enter your name and handle, then tap Save.",
    trigger: { type: "event", name: "ap_onboarding_profile_saved" },
  },

  // Phase 2 — App tour (only after profile saved)
  {
    id: "profile_saved",
    phase: ONBOARDING_PHASE_SETUP,
    route: "/profile",
    target: null,
    title: "Profile Saved",
    description: "Let's take a quick tour.",
    body: "Let's take a quick tour.",
    type: "modal",
    buttonText: "Start Tour",
    canAdvanceManually: true,
    trigger: { type: "button", action: "start_tour" },
  },
  {
    id: "tour_workouts",
    phase: ONBOARDING_PHASE_TOUR,
    route: "/workouts",
    target: "[data-onboarding='workouts-add']",
    title: "Workouts",
    description: "This is where you log workouts.",
    canAdvanceManually: true,
    allowSkip: true,
    trigger: { type: "button", action: "next_or_skip_tour" },
  },
  {
    id: "tour_overview",
    phase: ONBOARDING_PHASE_TOUR,
    route: "/workouts",
    target: "[data-onboarding='nav-tabs']",
    title: "Track progress",
    description: "ArmPal tracks workouts, PRs, measurements, nutrition, and goals.",
    canAdvanceManually: true,
    trigger: { type: "button", action: "next" },
  },
  {
    id: "tour_friends_nav",
    phase: ONBOARDING_PHASE_TOUR,
    route: "/",
    target: "[data-onboarding='friends-button']",
    title: "Friends",
    description: "Open the friends page.",
    requiredAction: "navigate",
    canAdvanceManually: false,
    advanceWhenRouteIs: "/friends",
    trigger: null,
  },
  {
    id: "tour_add_friend",
    phase: ONBOARDING_PHASE_TOUR,
    route: "/friends",
    target: "[data-onboarding='add-friend-button']",
    title: "Add friend",
    description: "Add a friend by handle to start a conversation.",
    canAdvanceManually: true,
    trigger: { type: "button", action: "next" },
  },
  {
    id: "tour_profile_settings_icon",
    phase: ONBOARDING_PHASE_TOUR,
    route: "/profile",
    target: "[data-onboarding='settings-button']",
    title: "Profile settings",
    description: "Open settings.",
    requiredAction: "click",
    canAdvanceManually: false,
    trigger: { type: "event", name: "ap_settings_opened" },
  },
  {
    id: "tour_profile_settings_panel",
    phase: ONBOARDING_PHASE_TOUR,
    route: "/profile",
    target: "[data-onboarding='settings-panel']",
    title: "Settings",
    description: "Customize ArmPal’s appearance and settings here.",
    canAdvanceManually: true,
    trigger: { type: "button", action: "next" },
  },
  {
    id: "tour_complete",
    phase: ONBOARDING_PHASE_TOUR,
    route: "/",
    target: null,
    title: "You're all set.",
    description:
      "Create workouts, track progress, and train with friends. Upgrade to Pro for advanced analytics and AI.",
    trigger: { type: "button", action: "finish" },
  },
];

